// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDj3vt7pQmkWqL3X6pG0qCoPNlgEoYdjY',
    appId: '1:251215461494:web:55e4506fa8c43da4e93357',
    messagingSenderId: '251215461494',
    projectId: 'quiz-75a2e',
    authDomain: 'quiz-75a2e.firebaseapp.com',
    storageBucket: 'quiz-75a2e.appspot.com',
    measurementId: 'G-5VLBDNYFYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5EEQMnE2xqO8lZlB9dVxehZ7FEj6DKeA',
    appId: '1:251215461494:android:1f2fbd5a382c7d65e93357',
    messagingSenderId: '251215461494',
    projectId: 'quiz-75a2e',
    storageBucket: 'quiz-75a2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxPr-dvzM9K9Z1ENlHEi7gKj8XzvkQ5r4',
    appId: '1:251215461494:ios:043c7805c3161606e93357',
    messagingSenderId: '251215461494',
    projectId: 'quiz-75a2e',
    storageBucket: 'quiz-75a2e.appspot.com',
    iosClientId: '251215461494-nt9sip8gld4f3pve7290lem0ggflimok.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz',
  );
}
